[package]
name = "sharder"
version = "0.1.0"
authors = ["rxdn"]
edition = "2018"
default-run = "public"

[dependencies]
cache = { path = "../cache" }
model = { path = "../model" }
common = { path = "../common" }
database = { path = "../database" }
tokio = { version = "1.2", features = ["full", "time", "sync", "signal"] }
tokio-tungstenite = { version = "0.15", features = ["rustls-tls", "webpki-roots"] }
webpki = "0.21.4"
url = "2.1"
futures = "0.3"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde_repr = "0.1"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
redis = { version = "0.17", features = ["tokio-rt-core", "connection-manager"] }
deadpool = { version = "0.5", features = ["managed"] }
deadpool-redis = "0.6"
jemallocator = "0.3"
simd-json = "0.3"
reqwest = { version = "0.11", features = ["json", "rustls-tls-webpki-roots"] }
flate2 = { version = "1.0", features = ["tokio", "zlib-ng-compat"], default-features = false, optional = true }
log = "0.4"
env_logger = "0.9"
envy = "0.4"
sentry = { version = "0.23", features = ["log"] }
sentry-log = "0.23"

[features]
default = ["skip-initial-guild-creates"]
compression = ["flate2", "reqwest/gzip"]
whitelabel = []
skip-initial-guild-creates = []

[[bin]]
name = "public"
allow-non-simd = true

[[bin]]
name = "whitelabel"
required-features = ["whitelabel"]
